### ISSUE TITLE
"window not defined" in server side rendering 

### ISSUE THREAD

**Issue by mmealling** [MichalZalecki/react-boilerplate-lite#9]
I'm using the not-so-lite branch and I'm getting this:
```
ReferenceError: window is not defined
    at eval (webpack:///./node_modules/httpplease/lib/xhr-browser.js?:1:18)
    at Object.<anonymous> (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:380:1)
    at __webpack_require__ (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:20:30)
    at eval (webpack:///./node_modules/httpplease/lib/index.js?:5:9)
    at Object.<anonymous> (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:367:1)
    at __webpack_require__ (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:20:30)
    at eval (webpack:///./src/common/App/App.jsx_+_76_modules?:3159:11)
    at Object.<anonymous> (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:313:1)
    at __webpack_require__ (/Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:20:30)
    at /Users/michaelmealling/Projects/MoonSociety/moon/build/app.server.js:63:18
```
This crops up in webpack 4 but supposedly isn't an issue in webpack 3. Have you run across this problem?

**Comment by MichalZalecki** [comment]
Use window (and other browser APIs) in code which is not run on the server. E.g. in componentDidMount
